# -*- coding: utf-8 -*-

# Form implementation generated from reading ui file 'E:\Senior Design\WaterDispenser\Windows\AddingNewUser.ui'
#
# Created by: PyQt5 UI code generator 5.14.2
#
# WARNING! All changes made in this file will be lost!


from PyQt5 import QtCore, QtGui, QtWidgets


class Ui_AddingNewUser(object):
    def setupUi(self, AddingNewUser):
        AddingNewUser.setObjectName("AddingNewUser")
        AddingNewUser.resize(800, 480)
        AddingNewUser.setMinimumSize(QtCore.QSize(800, 480))
        AddingNewUser.setMaximumSize(QtCore.QSize(800, 480))
        AddingNewUser.setFocusPolicy(QtCore.Qt.ClickFocus)
        AddingNewUser.setAccessibleName("")
        AddingNewUser.setStyleSheet("")
        self.gridLayout = QtWidgets.QGridLayout(AddingNewUser)
        self.gridLayout.setObjectName("gridLayout")
        spacerItem = QtWidgets.QSpacerItem(20, 10, QtWidgets.QSizePolicy.Minimum, QtWidgets.QSizePolicy.Fixed)
        self.gridLayout.addItem(spacerItem, 0, 0, 1, 1)
        self.horizontalLayout_6 = QtWidgets.QHBoxLayout()
        self.horizontalLayout_6.setObjectName("horizontalLayout_6")
        spacerItem1 = QtWidgets.QSpacerItem(40, 20, QtWidgets.QSizePolicy.Expanding, QtWidgets.QSizePolicy.Minimum)
        self.horizontalLayout_6.addItem(spacerItem1)
        self.label = QtWidgets.QLabel(AddingNewUser)
        self.label.setStyleSheet("font-size: 24px;")
        self.label.setAlignment(QtCore.Qt.AlignCenter)
        self.label.setObjectName("label")
        self.horizontalLayout_6.addWidget(self.label)
        spacerItem2 = QtWidgets.QSpacerItem(40, 20, QtWidgets.QSizePolicy.Expanding, QtWidgets.QSizePolicy.Minimum)
        self.horizontalLayout_6.addItem(spacerItem2)
        self.gridLayout.addLayout(self.horizontalLayout_6, 1, 0, 1, 1)
        spacerItem3 = QtWidgets.QSpacerItem(20, 25, QtWidgets.QSizePolicy.Minimum, QtWidgets.QSizePolicy.Fixed)
        self.gridLayout.addItem(spacerItem3, 2, 0, 1, 1)
        self.horizontalLayout_5 = QtWidgets.QHBoxLayout()
        self.horizontalLayout_5.setObjectName("horizontalLayout_5")
        spacerItem4 = QtWidgets.QSpacerItem(40, 20, QtWidgets.QSizePolicy.Expanding, QtWidgets.QSizePolicy.Minimum)
        self.horizontalLayout_5.addItem(spacerItem4)
        self.horizontalLayout = QtWidgets.QHBoxLayout()
        self.horizontalLayout.setObjectName("horizontalLayout")
        self.label_2 = QtWidgets.QLabel(AddingNewUser)
        self.label_2.setStyleSheet("font-size: 20px;\n"
"")
        self.label_2.setObjectName("label_2")
        self.horizontalLayout.addWidget(self.label_2)
        self.firstNameEdit = QtWidgets.QLineEdit(AddingNewUser)
        self.firstNameEdit.setFocusPolicy(QtCore.Qt.ClickFocus)
        self.firstNameEdit.setAcceptDrops(False)
        self.firstNameEdit.setStyleSheet("font-size: 20px;")
        self.firstNameEdit.setAlignment(QtCore.Qt.AlignCenter)
        self.firstNameEdit.setObjectName("firstNameEdit")
        self.horizontalLayout.addWidget(self.firstNameEdit)
        self.horizontalLayout_5.addLayout(self.horizontalLayout)
        spacerItem5 = QtWidgets.QSpacerItem(40, 20, QtWidgets.QSizePolicy.Expanding, QtWidgets.QSizePolicy.Minimum)
        self.horizontalLayout_5.addItem(spacerItem5)
        self.gridLayout.addLayout(self.horizontalLayout_5, 3, 0, 1, 1)
        spacerItem6 = QtWidgets.QSpacerItem(20, 10, QtWidgets.QSizePolicy.Minimum, QtWidgets.QSizePolicy.Fixed)
        self.gridLayout.addItem(spacerItem6, 4, 0, 1, 1)
        self.horizontalLayout_3 = QtWidgets.QHBoxLayout()
        self.horizontalLayout_3.setObjectName("horizontalLayout_3")
        spacerItem7 = QtWidgets.QSpacerItem(40, 20, QtWidgets.QSizePolicy.Expanding, QtWidgets.QSizePolicy.Minimum)
        self.horizontalLayout_3.addItem(spacerItem7)
        self.horizontalLayout_2 = QtWidgets.QHBoxLayout()
        self.horizontalLayout_2.setObjectName("horizontalLayout_2")
        self.label_3 = QtWidgets.QLabel(AddingNewUser)
        self.label_3.setStyleSheet("font-size: 20px;\n"
"")
        self.label_3.setObjectName("label_3")
        self.horizontalLayout_2.addWidget(self.label_3)
        self.lastNameEdit = QtWidgets.QLineEdit(AddingNewUser)
        self.lastNameEdit.setFocusPolicy(QtCore.Qt.ClickFocus)
        self.lastNameEdit.setAcceptDrops(False)
        self.lastNameEdit.setStyleSheet("font-size: 20px;")
        self.lastNameEdit.setAlignment(QtCore.Qt.AlignCenter)
        self.lastNameEdit.setObjectName("lastNameEdit")
        self.horizontalLayout_2.addWidget(self.lastNameEdit)
        self.horizontalLayout_3.addLayout(self.horizontalLayout_2)
        spacerItem8 = QtWidgets.QSpacerItem(40, 20, QtWidgets.QSizePolicy.Expanding, QtWidgets.QSizePolicy.Minimum)
        self.horizontalLayout_3.addItem(spacerItem8)
        self.gridLayout.addLayout(self.horizontalLayout_3, 5, 0, 1, 1)
        spacerItem9 = QtWidgets.QSpacerItem(20, 10, QtWidgets.QSizePolicy.Minimum, QtWidgets.QSizePolicy.Fixed)
        self.gridLayout.addItem(spacerItem9, 6, 0, 1, 1)
        self.horizontalLayout_7 = QtWidgets.QHBoxLayout()
        self.horizontalLayout_7.setObjectName("horizontalLayout_7")
        spacerItem10 = QtWidgets.QSpacerItem(40, 20, QtWidgets.QSizePolicy.Expanding, QtWidgets.QSizePolicy.Minimum)
        self.horizontalLayout_7.addItem(spacerItem10)
        self.horizontalLayout_8 = QtWidgets.QHBoxLayout()
        self.horizontalLayout_8.setObjectName("horizontalLayout_8")
        self.label_4 = QtWidgets.QLabel(AddingNewUser)
        self.label_4.setStyleSheet("font-size: 20px;\n"
"")
        self.label_4.setObjectName("label_4")
        self.horizontalLayout_8.addWidget(self.label_4)
        self.currentWeightEdit = QtWidgets.QLineEdit(AddingNewUser)
        self.currentWeightEdit.setFocusPolicy(QtCore.Qt.ClickFocus)
        self.currentWeightEdit.setAcceptDrops(False)
        self.currentWeightEdit.setStyleSheet("font-size: 20px;")
        self.currentWeightEdit.setAlignment(QtCore.Qt.AlignCenter)
        self.currentWeightEdit.setObjectName("currentWeightEdit")
        self.horizontalLayout_8.addWidget(self.currentWeightEdit)
        self.horizontalLayout_7.addLayout(self.horizontalLayout_8)
        spacerItem11 = QtWidgets.QSpacerItem(40, 20, QtWidgets.QSizePolicy.Expanding, QtWidgets.QSizePolicy.Minimum)
        self.horizontalLayout_7.addItem(spacerItem11)
        self.gridLayout.addLayout(self.horizontalLayout_7, 7, 0, 1, 1)
        self.errorLoggingLabel = QtWidgets.QLabel(AddingNewUser)
        self.errorLoggingLabel.setEnabled(False)
        self.errorLoggingLabel.setStyleSheet("QLabel{\n"
"    font-size: 15px;\n"
"    color: red;\n"
"}")
        self.errorLoggingLabel.setText("")
        self.errorLoggingLabel.setAlignment(QtCore.Qt.AlignCenter)
        self.errorLoggingLabel.setWordWrap(True)
        self.errorLoggingLabel.setObjectName("errorLoggingLabel")
        self.gridLayout.addWidget(self.errorLoggingLabel, 8, 0, 1, 1)
        spacerItem12 = QtWidgets.QSpacerItem(17, 41, QtWidgets.QSizePolicy.Minimum, QtWidgets.QSizePolicy.Expanding)
        self.gridLayout.addItem(spacerItem12, 10, 0, 1, 1)
        self.horizontalLayout_4 = QtWidgets.QHBoxLayout()
        self.horizontalLayout_4.setObjectName("horizontalLayout_4")
        spacerItem13 = QtWidgets.QSpacerItem(150, 20, QtWidgets.QSizePolicy.Expanding, QtWidgets.QSizePolicy.Minimum)
        self.horizontalLayout_4.addItem(spacerItem13)
        self.backButton = QtWidgets.QPushButton(AddingNewUser)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Expanding, QtWidgets.QSizePolicy.Expanding)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.backButton.sizePolicy().hasHeightForWidth())
        self.backButton.setSizePolicy(sizePolicy)
        self.backButton.setStyleSheet("font-size: 18px;")
        self.backButton.setAutoDefault(False)
        self.backButton.setObjectName("backButton")
        self.horizontalLayout_4.addWidget(self.backButton)
        spacerItem14 = QtWidgets.QSpacerItem(80, 20, QtWidgets.QSizePolicy.Fixed, QtWidgets.QSizePolicy.Minimum)
        self.horizontalLayout_4.addItem(spacerItem14)
        self.saveAndReturnButton = QtWidgets.QPushButton(AddingNewUser)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Expanding, QtWidgets.QSizePolicy.Expanding)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.saveAndReturnButton.sizePolicy().hasHeightForWidth())
        self.saveAndReturnButton.setSizePolicy(sizePolicy)
        self.saveAndReturnButton.setStyleSheet("font-size: 18px;")
        self.saveAndReturnButton.setAutoDefault(False)
        self.saveAndReturnButton.setObjectName("saveAndReturnButton")
        self.horizontalLayout_4.addWidget(self.saveAndReturnButton)
        spacerItem15 = QtWidgets.QSpacerItem(40, 20, QtWidgets.QSizePolicy.Expanding, QtWidgets.QSizePolicy.Minimum)
        self.horizontalLayout_4.addItem(spacerItem15)
        self.saveAndContinueButton = QtWidgets.QPushButton(AddingNewUser)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Expanding, QtWidgets.QSizePolicy.Expanding)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.saveAndContinueButton.sizePolicy().hasHeightForWidth())
        self.saveAndContinueButton.setSizePolicy(sizePolicy)
        self.saveAndContinueButton.setStyleSheet("font-size: 18px;")
        self.saveAndContinueButton.setAutoDefault(False)
        self.saveAndContinueButton.setObjectName("saveAndContinueButton")
        self.horizontalLayout_4.addWidget(self.saveAndContinueButton)
        spacerItem16 = QtWidgets.QSpacerItem(40, 20, QtWidgets.QSizePolicy.Expanding, QtWidgets.QSizePolicy.Minimum)
        self.horizontalLayout_4.addItem(spacerItem16)
        self.gridLayout.addLayout(self.horizontalLayout_4, 11, 0, 1, 1)
        spacerItem17 = QtWidgets.QSpacerItem(20, 41, QtWidgets.QSizePolicy.Minimum, QtWidgets.QSizePolicy.Expanding)
        self.gridLayout.addItem(spacerItem17, 12, 0, 1, 1)

        self.retranslateUi(AddingNewUser)
        QtCore.QMetaObject.connectSlotsByName(AddingNewUser)

    def retranslateUi(self, AddingNewUser):
        _translate = QtCore.QCoreApplication.translate
        AddingNewUser.setWindowTitle(_translate("AddingNewUser", "AddingNewUser"))
        self.label.setText(_translate("AddingNewUser", "Create New User"))
        self.label_2.setText(_translate("AddingNewUser", "First Name: "))
        self.firstNameEdit.setPlaceholderText(_translate("AddingNewUser", "First Name"))
        self.label_3.setText(_translate("AddingNewUser", "Last Name: "))
        self.lastNameEdit.setPlaceholderText(_translate("AddingNewUser", "Last Name"))
        self.label_4.setText(_translate("AddingNewUser", "Current weight"))
        self.currentWeightEdit.setPlaceholderText(_translate("AddingNewUser", "Current Weight"))
        self.backButton.setText(_translate("AddingNewUser", "Back"))
        self.saveAndReturnButton.setText(_translate("AddingNewUser", "Save and Return"))
        self.saveAndContinueButton.setText(_translate("AddingNewUser", "Save and Continue"))
